baseurl = "https://lukaszsiedlecki.com"
title = "Łukasz Siedlecki"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[pagination]
pagerSize = 20

#[services]
#[services.disqus]
#shortname = "https-lukaszsiedlecki-com"
[markup.highlight]
style = "github-dark"

[params]
author = "Łukasz Siedlecki"
info = "Software Engineer and DevOps passionate"
description = "Łukasz Siedlecki's personal website"
keywords = "blog,developer,personal"
avatarURL = "images/avatar.jpg"
#  gravatar = "me@lukaszsiedlecki.com"

faviconSVG = "/img/favicon.svg"
favicon_32 = "/img/favicon-32x32.png"
favicon_16 = "/img/favicon-16x16.png"

since = 2015

enableTwemoji = true

colorScheme = "auto"
hidecolorschemetoggle = false

# customCSS = ["css/custom.css"]
# customSCSS = ["scss/custom.scss"]
# customJS = ["js/custom.js"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/lukaszsiedlecki/"
target = "_blank"
[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/lukasz-siedlecki/"
target = "_blank"
[[params.social]]
name = "Email"
icon = "fa-solid fa-envelope fa-2x"
weight = 3
url = "mailto:me@lukaszsiedlecki.com"

# Menu links
[[menu.main]]
name = "Blog"
weight = 1
url = "posts/"
[[menu.main]]
name = "About"
weight = 2
url = "about/"